name: apex_plus
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_switch:
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.0.1
  clay_containers:
  curved_navigation_bar: ^0.3.3
  timer_builder: ^1.3.0
  gradient_app_bar:
  liquid_pull_to_refresh: ^1.1.1
  expansion_card:
  smooth_star_rating: ^1.1.1
  flutter_neumorphic:
  dropdownfield: ^1.0.3
  timeline_tile: 
  google_fonts: 
  flutter_highlight: 
  url_launcher: ^5.5.0
  flutter_showcase:
  chewie:
  video_player:
  rflutter_alert: ^1.0.3
  confetti: ^0.5.4

flutter:

  uses-material-design: true

  assets:
      - assets/video.mp4
      - assets/login_logo.png
      - images/
      - assets/img/argentina.png
      - assets/img/jubileu.png
      - assets/img/mariazinha.png
      - assets/img/acucar/
      - assets/img/cafe/
      - assets/img/celulose/

  fonts:
    - family: TitleFont
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: SpartanRegular
      fonts:
        - asset: assets/fonts/static/Spartan-Regular.ttf

    - family: SpartanLight
      fonts:
        - asset: assets/fonts/static/Spartan-Light.ttf